### ISSUE TITLE
BlockchainOptions#validate is too coarse

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-blockchain#120]
I'm working on a testing chain with this module and `ethereumjs-vm` and want to validate everything but POW. The reason I want to do it is that I want to spot every error asap, but I don't want to waste time on POW mining.

The problem is that the only way to disable POW verification is by setting `BlockchainOptions#validate` to `false`, and this also disables blocks' validation (i.e. calling `block.validate`).

I think we should have two separate options for this.

**Comment by s1na** [comment]
Makes sense. We could introduce an option either for validating blocks, or one for validating PoW, and for backwards-compatibility set it to `self.validate` by default.

**Comment by alcuadrado** [comment]
I found something weird while implementing this. 

`Blockchain#validate` can be modified from the outside, and the tests actually do it. But if you create a blockchain with `validate: false`, and then set it to true, it won't instantiate `ethash` in the constructor, so changing it to `true` renders the `Blockchain` unusable.

This makes me wonder how used is the validation feature, and especially, changing it after creation.

To be strict with semver, we should probably fix this and release a new major, but is it worth it if nobody was using it? Just thinking aloud. I don't have a strong opinion on this.

**Comment by holgerd77** [comment]
@alcuadrado Is this technically really a breaking change and not rather some bug fixing? Do you need this for your `validate` logic improvement development? Otherwise we could tackle separately and open a new issue?

**Comment by alcuadrado** [comment]
> Is this technically really a breaking change and not rather some bug fixing?

It's hard to tell. The original intention is not clear, and I have no idea who is consuming this library apart from the vm.

> Do you need this for your `validate` logic improvement development?

Yes, I'll use a setter that updates both `pow` and `blocks` validation flags.

---

BTW, I disabled blocks validation in my code. I'm using `VM#runBlock`, which already validates them, so `Blockchain#putBlock` was validating them a second time, taking slightly more time with no benefit.

**Comment by holgerd77** [comment]
I would tend to not do this as a major breaking release. Maybe just do your PR, I think we'll find a way how we do the process here.
