### ISSUE TITLE
Modernizing this library's tests

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-blockchain#125]
The tests of this library are extremely hard to work with. They are coded as a single `tape` tests, with lots of shared state between them. I tried to add a new test in #121, and couldn't make it run.

I tried to modernize them today, separating them in multiple tests, and removing the `asyn` library, but it is very hard to do so. I spent about half an hour on this and got to migrate 5 of ~40 tests, and I suspect they were by far the easiest to migrate, so I suspect this would take at least 4-5hs, and will be difficult to review.

As it will take some time, I'm opening this issue to get your opinion if this is something that we want in the short-term, @holgerd77, @s1na.

**Comment by holgerd77** [comment]
Would rather move this to midterm, one major thing we should ramp up short-term and which will take quite some capacity is the upcoming Istanbul integration in the VM (meta issue already there) and others.

**Comment by ryanio** [comment]
Fixed with #134 :)
