### ISSUE TITLE
Make sure test fixture is not outdated

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-blockchain#132]
I just noticed that this lib is using a static [fixture](https://github.com/ethereumjs/ethereumjs-blockchain/blob/0cf409e8c5d9f9e36a2d1ef7d584dafeafae35d3/test/testdata.json), i.e. not tests from `ethereumjs-testing` and the last commit of that file is in May 2018. I'm not sure if any HF since then has directly touched Blockchain's code, but at least in future it's possible.

The file seems to have been taken from the `BlockchainTests` suite, but many of the values are hardcoded in the unit tests. Ideally we should make this a bit more flexible and upgrade-able.

**Comment by holgerd77** [comment]
Also for reference: we should minimally also introduce some JSON metadata test file format with info like "source", "version", "commit" and "date" like being done [here](https://github.com/ethereumjs/rlp/pull/66/files#diff-226c9b95ed596d7728aae9b5f91f0648R1) for the `RLP` library.

**Comment by ryanio** [comment]
Fixed with #134
