### ISSUE TITLE
Coverage report ceased to work

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-blockchain#139]
Since the recent changes in the test suite #134, the Coverage report stopped working, leading to a wrong [0% test coverage](https://coveralls.io/builds/27524466) result.

It happened for the [first time in Travis](https://travis-ci.org/ethereumjs/ethereumjs-blockchain/jobs/623080431#L498) and it got carried over to the [GH actions](https://github.com/ethereumjs/ethereumjs-blockchain/runs/341775235#step:6:212).

**Comment by ryanio** [comment]
Thanks for the report, I will look into it and see what could be going on.

**Comment by evertonfraga** [comment]
Thanks! 

I think that might lead to a slightly broader discussion regarding how we're using Coveralls and how should it be used in conjunction with GH actions.

I put together [this gist](https://gist.github.com/evertonfraga/4e92aa627ad50284d5355de2c47b7693#file-gh-actions-yml) with how these reports are generated (npm run x) and how they are executed in GH actions.

I have some exploratory questions (that I can investigate myself as well)
- is `npm run coveralls` enough to send the reports?
- can it be fully replaced by `coverallsapp/github-action@master`?
- if so, we gotta choose one to use

**Comment by ryanio** [comment]
Ah yes I forgot to include the `.nycrc` code from Holger here https://github.com/ethereumjs/ethereumjs-blockchain/pull/134#issuecomment-560350726. I will open a PR for that now.

Good questions, I had some of the same questions, and also found this: https://github.com/ethereumjs/ethereumjs-config/issues/22
