### ISSUE TITLE
Example running existing geth data

### ISSUE THREAD

**Issue by big-kahuna-burger** [ethereumjs/ethereumjs-blockchain#68]
If someone could provide a working example on how to use this package to instantiate Blockchain class instance from existing geth data from disk, that would be awesome.

**Comment by vpulim** [comment]
@big-kahuna-burger There is a working example of loading and iterating through an existing geth database at the top of the README. However, there is currently an open issue (#66) in which the geth db may no longer be readable by geth after its loaded by this library. Just to be safe, I would make a backup of your geth db if you will need to load it with geth in the future.
