### ISSUE TITLE
NPM package doesn't contain the code for 3.3.1

### ISSUE THREAD

**Issue by vpulim** [ethereumjs/ethereumjs-blockchain#81]
The NPM package for version 3.3.1 seems to contain older code (3.3.0 I think). It doesn't have the fix that was part of the 3.3.1 changes. Is it possible to re-publish it?

**Comment by holgerd77** [comment]
Are you sure that this is not something which has been added afterwards? I can't really imagine how this would be possible in the current setup, nothing to build and on `npm` there wouldn't be a new version published with the version number in `package.json` not updated (so also not possible to have forgotten a ``git pull origin master`` or something).

Republishing is actually not possible (npm restrictions), can we do a follow up release? Do the latest changes allow for staying in the ``3.3.x`` real or would they need a more major version bump - haven't got the overview atm (then this wouldn't be fixed for people staying on the ``3.3`` branch)?

I will do some additional conversation via Gitter DM.

**Comment by vpulim** [comment]
@holgerd77 Sorry! Totally my mistake 🤦‍♂️ I misread the commit history... We would need to do a new release to include the `putBlocks()` fix I needed.
