### ISSUE TITLE
Auto-generated documentation with TSDocs

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-blockchain#95]
Documentation of this library should be auto-generated with `TypeDoc`, this PR https://github.com/ethereumjs/ethereumjs-util/pull/170 can serve as a reference (see also [technical docs on documentation](https://ethereumjs.readthedocs.io/en/latest/technical.html#documentation)).

For this the manual documentation comments in the `README` (https://github.com/ethereumjs/ethereumjs-account) should be integrated in the code along the way.

Only functionality in [index.ts](https://github.com/ethereumjs/ethereumjs-blockchain/blob/master/src/index.ts) is currently part of the external API and should be publicly exposed (so roughly the currently documented functions, apart from eventually some updates from recent changes or functionality additions).

**Comment by alcuadrado** [comment]
I migrated ethereumjs-tx to typedoc already. This should be pretty similar. I'll do it.

**Comment by alcuadrado** [comment]
The `Blockchain` class has lots of fields and methods starting with `_`, which I believe are private. Should we document them? If not, we can declare them as private and use typedoc's `--excludePrivate`.

**Comment by holgerd77** [comment]
@alcuadrado Great! 😄

No, ``_``-methods shouldn't be documented and rather be excluded, declaring as ``private`` is probably a valid way to go.
